### ISSUE TITLE
Define clearly how the capture IDL attribute is reflected

### ISSUE THREAD

**Issue by foolip** [w3c/html-media-capture#12]
https://w3c.github.io/html-media-capture/#the-capture-attribute says "The capture IDL attribute must reflect the respective content attribute of the same name." and links to https://html.spec.whatwg.org/multipage/infrastructure.html#reflect

However, the bit in HTML that defined how to reflect an enum was removed in https://github.com/whatwg/html/pull/2585. Probably the solution is to make the IDL attribute a DOMString, and handling it similarly to for example https://html.spec.whatwg.org/multipage/embedded-content.html#attr-track-kind

@annevk @domenic

**Comment by domenic** [comment]
Agreed. You could also do what we've been doing for other cases that avoids such a table, such as

> Each referrer policy, including the empty string, is a keyword for this attribute, mapping to a state of the same name.

or

> Each request destination, including the empty string, is a keyword for this attribute, mapping to a state of the same name.

The important thing though is to update all specs to refer to the *state* of the attribute, not the *value*, since e.g. the value could be "asdf", but the state will be whatever you've set the invalid value default to.
