### ISSUE TITLE
VideoFacingModeEnum as the capture attribute's value

### ISSUE THREAD

**Issue by anssiko** [w3c/html-media-capture#4]
See whatwg/html/issues/1102.

**Comment by legion80** [comment]
To reiterate, the use case here is that mobile web authors may want to provide a more convenient experience for their users to update their profile pictures. Since many smartphones have two cameras, this proposal allows the author to provide a hint to the user agent of which camera to use. If the hint cannot be obeyed, the user agent is free to fall back to the camera that is available.

Concretely, the proposal is to allow [`VideoFacingModeEnum`](http://w3c.github.io/mediacapture-main/#idl-def-VideoFacingModeEnum) as values to the `capture` attribute. I think `user` and `environment` are the most useful ones.

The proposal turns the IDL from
`attribute boolean capture;`
to
`attribute DOMString capture;`

which makes for one backwards incompatible change, which is that disabling capture via JS would no longer work:

```
document.getElementById("inputFileCapture").capture = false;
```

I think it's an acceptable tradeoff for a more streamlined flow of capturing with the right camera.

Any thoughts?

**Comment by anssiko** [comment]
I think this use case is a common one for the Web, and hooking into [`VideoFacingModeEnum`][1] to provide a better hint makes sense.

Given sufficient implementers' interest, we could update the spec accordingly.

[1]: https://w3c.github.io/mediacapture-main/#idl-def-videofacingmodeenum

**Comment by anssiko** [comment]
Chromium implementation just landed: https://chromium.googlesource.com/chromium/src/+/08c2a170239dae6559f696d033fa1baf8bbef4ac

Thanks @riju!
